# Generated by Django 4.2.11 on 2024-05-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
